### ISSUE TITLE
Status Band Color

### ISSUE THREAD

**Issue by oniram307** [FreEZer00/teams-webhook-action#138]
Hi.  We've been using this github action, and it works great for our use case.  However, we had one minor request I wanted to get on your radar.  Right now the status band isn't configurable and is always 'green'.  It would be great if we could customize that so we could make it red.  It would help the posts standout better in our use case.  If that's possible, let me know.  Thanks.

**Comment by FreEZer00** [comment]
Hi @oniram307 
Can you maybe elaborate on what you are trying to achieve? You are right, this color is not configurable but it is not fixed. 
The color can change depending on the configuration/input. 
So for example if you are using it in a workflow this job can change the notification color depending on previous jobs of the workflow that are added to the needs of the notification job (as long as the needs are passed as a json string as well)

Here a small example: 

`
  testJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          exit 1
  verifyAction: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    needs: [ testJob ]
    if: ${{always()}}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          webhook_url: ${{secrets.webhook}}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          title: Custom title
`

Note that here the testJob exits with exit code 1. In that case this job fails but the notification is still triggered due to the `if: ${{always()}}`. The needs are passed by `needs: ${{ toJson(needs) }}` . 

Base on the [overall status](https://github.com/FreEZer00/teams-webhook-action/blob/main/src/service/webhook.ts#L29) the [color](https://github.com/FreEZer00/teams-webhook-action/blob/main/src/service/webhook.ts#L20) is determined for the notification.

Does that help you already or do you still need a way of manually configuring the color?

**Comment by FreEZer00** [comment]
As a further example check out this [workflow run](https://github.com/FreEZer00/teams-webhook-action/actions/runs/5579385593)
[Workflow file](https://github.com/FreEZer00/teams-webhook-action/actions/runs/5579385593/workflow#L49)

Output theme color: `"themeColor": "#b80707"`

**Comment by oniram307** [comment]
Ok, that did the trick.  Didn't pick up on that earlier.  Thanks for pointing that out.  One other question.  In the image below, output indicated?  It seems to be grabbing the filename "execute.yml" and stripping of the extension for the name.  However, the formal name for the workflow file defined in the "name" field is "Execute Workflow".  Is it possible to use that instead?

<img width="1046" alt="image" src="https://github.com/FreEZer00/teams-webhook-action/assets/37271796/2ef73cbd-d3c6-425b-a577-2cc0adb2fa98">

**Comment by FreEZer00** [comment]
The execute job you marked is not the workflow name but the need that is configured for the notification. As you see in the title it says "execute workflow" 
Execute is just one job in your Workflow that fails and causes the whole workflow to fail. If you want to see the workflow name there as well just rename the execute job to execute-workflow. 

In case you had more needs configured for the notification they would all be listed in the notification with their success status

Hope that helps

**Comment by oniram307** [comment]
Yup, get it now.  Thanks for the explanation.  If feasible, maybe consider adjusting the output to read like the below to make to remove any ambiguity?  

Job: execute
Status: failure

**Comment by oniram307** [comment]
Also, is there any option to suppress that line if I wanted to?

**Comment by FreEZer00** [comment]
> Yup, get it now. Thanks for the explanation. If feasible, maybe consider adjusting the output to read like the below to make to remove any ambiguity?
> 
> Job: execute Status: failure

The undelying data structure is a key value pair that I am using to display the job an each status. I currently prefer it that way but I will think about it. 


> Also, is there any option to suppress that line if I wanted to?

I will add a flag for you to omit this output and not display the job statuses :)

**Comment by FreEZer00** [comment]
Checkout release v1.3.0

**Comment by oniram307** [comment]
Fantastic.  Thank you so much.
